### ISSUE TITLE
Make the list of static social networks filterable

### ISSUE THREAD

**Issue by BinaryMoon** [BinaryMoon/wp-toolbelt#10]
Add a filter for the social networks so they can be added & edited.

In principle this is simple but I need to work out an elegant way to make the svg icons work.

Perhaps there could be an optional 'image' parameter. By default the plugin uses the key to work out the icon location, but if the image param exists that could be used instead?

**Comment by ndegruchy** [comment]
This was fixed in #99, though I didn't implement adding your own, or implementing custom images. Those would be next steps. Seems pretty doable, too. I'll look at it at some point.

**Comment by BinaryMoon** [comment]
I think this is done now so I'm closing it.
