### ISSUE TITLE
Star Rating block

### ISSUE THREAD

**Issue by richardmtl** [BinaryMoon/wp-toolbelt#109]
Hi! Jetpack has a [Star Rating block](https://jetpack.com/support/jetpack-blocks/star-rating-block/); do you think you could add something similar?

**Comment by BinaryMoon** [comment]
Thanks for the suggestion. I'll definitely think about that!

**Comment by richardmtl** [comment]
If you DO add something better, you know what would make it even better (at least for my purposes, ha!): make it linkable somehow. Meaning, if I'm showing 5 stars, and a rating of 2/5, allow the site visitor to click the 2nd filled-in star, and that click will take the visitor to an archive page that shows all other 2/5 posts/pages/CPTs that have that rating..  Though maybe we're getting a bit too complicated for your plugin, and merits it's own stand-alone plugin for star ratings with additional options such as that.

**Comment by BinaryMoon** [comment]
That's an interesting idea. I don't know how I would do it without adding custom post types/ taxonomies, but I'll keep it in mind.

**Comment by BinaryMoon** [comment]
Hi - this will be in the next version of the plugin 👍 

Thanks for the suggestion.
