### ISSUE TITLE
Feature request - simple per page password restricted content

### ISSUE THREAD

**Issue by loftwah** [BinaryMoon/wp-toolbelt#118]
https://wordpress.org/plugins/password-protect-page/ is an example of the plugin that this module/feature would replace.

**Comment by BinaryMoon** [comment]
Hey - thanks for the idea!

I'm not familiar with this sort of thing since I have never had a need for it, how would this differ from the built in post password functionality, and why can't you use the plugin you linked?

Thanks again!

**Comment by loftwah** [comment]
There is no reason not to use the other plugin, I just figured it might be something useful for the toolbelt. I could always put something together in another branch.

**Comment by BinaryMoon** [comment]
If you want to take a stab at adding it in a new branch I'd love to take a look.

My philosophy when making these things is to keep it as simple as possible, and to use core things as much as possible. For instance if I were making this I would try to reuse the post password html output, which would mean theme styles for the core feature should work on the new feature as well.

**Comment by loftwah** [comment]
> If you want to take a stab at adding it in a new branch I'd love to take a look.
> 
> My philosophy when making these things is to keep it as simple as possible, and to use core things as much as possible. For instance if I were making this I would try to reuse the post password html output, which would mean theme styles for the core feature should work on the new feature as well.

I wanted to recommend it because your plugin has sparked an idea for me. I need to take some time to work out how your modular system works and I figure it should be pretty easy to slide them in and out (almost like a plugin system within a plugin system). I like to leverage heaps of tiny little plugins but I hate having a huge list, rather than make my own custom plugin I think your idea might work.

**Comment by BinaryMoon** [comment]
That's pretty much what Toolbelt is - all the modules are very small plugins.

There's a big array in the root index.php that holds all the modules. Add a new entry there, and then a new module with the same name as the key and you can then enable it through the settings page.

**Comment by loftwah** [comment]
Nice one, I had a quick look before. There are so many great plugins out there that wreck everything by adding their own visual components everywhere. I like it simple, your plugin is different because it is a parent plugin but if it creates its own menu or too many nags/ads its a no go for me mostly (or a reluctant usage). Any menu should be in Tools or Settings as a submenu, in this case, you've got your own parent with submodules which adds one menu max (and is easily changed).
