### ISSUE TITLE
Markdown block and shortcodes

### ISSUE THREAD

**Issue by tbdalgaard** [BinaryMoon/wp-toolbelt#119]
Is it possible to combine Markdown in the Markdown block and entering short codes as in the classic editor, or is this impossible?

**Comment by BinaryMoon** [comment]
Hi there - thanks for the message. I don't know how hard this would be but I don't think it would be too hard so I'd be happy to take a look some time.

Thanks for the suggestion.

**Comment by BinaryMoon** [comment]
I've just tested this and it seems to work already. No changes needed.

I noticed urls are auto converted so I will disable that. If I don't then urls parameters will get converted, but otherwise it all works fine as is.

**Comment by tbdalgaard** [comment]
Nice, from reading the docs I wasn't sure that this would work.
I didn't know either which flavours of Markdown WP-ToolBelt can support, and if there are any settings after enabling the module.

Regarding short-codes, I will test this in a near future and reply here, if I run into something unexpected. :)

**Comment by BinaryMoon** [comment]
I didn't know whether it was possible or not either. It's not something I had considered before.

I have updated the docs to reflect the findings :)

https://github.com/BinaryMoon/wp-toolbelt/wiki/Markdown
