### ISSUE TITLE
Question re: my_related_posts_type

### ISSUE THREAD

**Issue by paulburgess** [BinaryMoon/wp-toolbelt#12]
Hi, great plugin but I'm a bit confused by this part of my_related_posts_type:

https://github.com/BinaryMoon/wp-toolbelt/wiki/Related-Posts#toolbelt_related_posts_types

Is the example code correct, with the reference to toolbelt_portfolio_related_posts_type? Does it mean I can display related custom post types?

For example - if want to display related 'event' post types, on a single event, with the same 'event-type' taxonomy... is that this offers? By doing this:

```
$types['event'] = 'event-type';
```

Many thanks!

**Comment by BinaryMoon** [comment]
Hey Paul - thanks for the feedback.

> Is the example code correct, with the reference to toolbelt_portfolio_related_posts_type? Does it mean I can display related custom post types?

Yeah, you can add support for any custom post types that your theme or plugin supports. Assuming those slugs are what you use in your event plugin then yes, that should work!

**Comment by BinaryMoon** [comment]
I've just realised I had the filter name wrong in the code sample. I've updated it so the example works properly.
