### ISSUE TITLE
blacklist_keys is deprecated

### ISSUE THREAD

**Issue by Zodiac1978** [BinaryMoon/wp-toolbelt#123]
The usage of `blacklist_keys` is deprecated with WordPress 5.5:

Is used here:
https://github.com/BinaryMoon/wp-toolbelt/blob/dcce984fdc9442c4f77d9f23d0c3aa562b0c21e2/modules/spam-blocker/module.php#L189

See this dev note for details:
https://make.wordpress.org/core/2020/07/23/codebase-language-improvements-in-5-5/

**Comment by Zodiac1978** [comment]
I think the filter needs to be renamed also:
https://github.com/BinaryMoon/wp-toolbelt/blob/dcce984fdc9442c4f77d9f23d0c3aa562b0c21e2/modules/spam-blocker/module.php#L267

There was just a short timeframe where this option was named `blocklist_keys` (was `blacklist_keys` and in the final release it was `disallowed_keys`).

`option_blocklist_keys` therefore should become `option_disallowed_keys` for WP 5.5+

**Comment by BinaryMoon** [comment]
Hi there - thanks for this! 👍 
I actually found this a couple of days ago, I hadn't noticed it before but found that spam checking wasn't working properly. So it was updated in the last plugin update, but I hadn't merged from the dev branch so master was behind.

I've now merged the changes.
https://github.com/BinaryMoon/wp-toolbelt/blob/master/modules/spam-blocker/module.php#L190-L191

https://github.com/BinaryMoon/wp-toolbelt/blob/master/modules/spam-blocker/module.php#L270-L271

I've kept the old option and filter for people who haven't updated to the latest version of WordPress.

I've tested and think this is working now but if you want to check as well I'd appreciate confirmation that it works as expected.

Thanks again

**Comment by Zodiac1978** [comment]
> I hadn't merged from the dev branch so master was behind

Sorry, I haven't checked that :(

> I've kept the old option and filter for people who haven't updated to the latest version of WordPress.

This will result in a public warning if Debug mode is on. I think it is recommended to check for the WP version like in the example mentioned in the linked post.

**Comment by BinaryMoon** [comment]
Ah - good point. I'll update that as well.

Thanks again
