### ISSUE TITLE
image optimizing CDN

### ISSUE THREAD

**Issue by nosilver4u** [BinaryMoon/wp-toolbelt#13]
I was reading about your new plugin on WP Tavern today, and it mentioned that some things, like an image CDN and statistics, would be difficult to implement since it seems you are trying to be very privacy-focused with this plugin.

I share your concerns about the performance of JetPack, and am very much in the business of helping folks make their sites performant (EWWW Image Optimizer), so I wanted to reach out to you directly. Unfortunately, your contact form wasn't working for me, so here I am!

If you're ever interested in adding some sort of image-optimizing CDN to the Toolbelt, please reach out to me at https://ewww.io/contact-us/
We do our best to be very privacy-oriented, with our zero-storage optimization API, and we don't log any user data on our image-optimizing CDN (ExactDN). We just recently released a very lean version of our ExactDN service + lazy loading called Easy Image Optimizer, and I think it could be a great fit for your target audience.

Take care,
Shane Bishop
EWWW IO

**Comment by BinaryMoon** [comment]
Hi Shane - thanks. I've fixed the contact form now.

I shall drop you an email.

Cheers - Ben
