### ISSUE TITLE
PHP warnings if social sharing settings are empty

### ISSUE THREAD

**Issue by walterebert** [BinaryMoon/wp-toolbelt#135]
If the social sharing settings are not set, I get PHP warnings.

Warning: Undefined array key "social-sharing" in wp-content/plugins/wp-toolbelt/modules/social-sharing/module.php:335

On the Toolbelt settings page:
Warning: Undefined array key "social-sharing in wp-content/plugins/wp-toolbelt/modules/social-sharing/settings.php:17

**Comment by walterebert** [comment]
Fix has been merged into dev https://github.com/BinaryMoon/wp-toolbelt/pull/136

**Comment by BinaryMoon** [comment]
Hi - really sorry. I thought I'd updated you here.

I added the fix because of your pull request, not sure why I didn't merge it the normal way.

I appreciate the pull request, thanks a lot for the contribution!
