### ISSUE TITLE
Footnotes top padding

### ISSUE THREAD

**Issue by topher1kenobe** [BinaryMoon/wp-toolbelt#139]
When clicking a footnote number it zips down to the footnote, and when you click back to the return arrow it zips back the link.  This is great, except when you're logged into the site. The admin bar hides both the link and the footnote (if the footnote is short enough).  Screenshot attached.

Recommended fix: check for logged in user and provide the proper padding at the top.

<img width="1072" alt="Screen Shot 2021-06-06 at 5 31 03 PM" src="https://user-images.githubusercontent.com/341412/120940833-2b3e8b00-c6ed-11eb-9499-9891513ae2ba.png">

**Comment by BinaryMoon** [comment]
Hi Topher - thanks for the report. There's a css fix in the plugin but it seems it's not always loaded so I've updated the plugin to make sure it is loaded when needed.

https://github.com/BinaryMoon/wp-toolbelt/commit/99a7b1240d2d7f8916d991eba15243aa05965de0

I published the update just now - let me know if it doesn't work prooperly.

Thanks!

**Comment by topher1kenobe** [comment]
Nailed it, thanks!
