### ISSUE TITLE
Adding Links to Related Posts Thumbnails

### ISSUE THREAD

**Issue by wpgaurav** [BinaryMoon/wp-toolbelt#146]
Hi Ben, I have started using Toolbelt on gauravtiwari.org and I am loving it so far. I was wondering if there is already a way I could link thumbnails in related posts as well. This will definitely improve the bounce rate.

**Comment by BinaryMoon** [comment]
Hi there - thanks for the message.

The related post images "should" link to the post already, but perhaps there's something wrong with the CSS that stops it from working on your site. Do you have a link to a page with the problem that I could take a look at?

**Comment by wpgaurav** [comment]
Hi @BinaryMoon , Please see this https://gauravtiwari.org/online-teaching-website-with-wordpress/

**Comment by BinaryMoon** [comment]
Thanks - I can see why that is happening. The simplest solution would be to change the html so that the image is linked, so I'll do that in the next update.

thanks for the report!

**Comment by wpgaurav** [comment]
You are awesome. It works great now. Thank you so much.

**Comment by BinaryMoon** [comment]
Awesome - glad it worked! :)
