### ISSUE TITLE
Custom message on cookie banner and button

### ISSUE THREAD

**Issue by naymapl** [BinaryMoon/wp-toolbelt#16]
Hi. I try to use custom text for cookie banner message. I use this code but nothing happends.

function my_cookie_banner_message( $message ) {
    return 'My site uses cookies!';
}
add_filter( 'tb_cookie_message', 'my_cookie_banner_message' );

And how to change text on accept button for cookie banner. Thanks a lot for any suggestions and help.

**Comment by BinaryMoon** [comment]
Hi there - thanks for the message.

I think I changed the filter and didn't update the docs. It should be `toolbelt_cookie_message`. I have updated the docs to show the correct filter name.

For the button text, that's a good idea. I shall add a filter for editing them. I've  made the changes, and added docs for this. It will be in the next plugin update.
https://github.com/BinaryMoon/wp-toolbelt/wiki/Cookie-Banner

**Comment by naymapl** [comment]
Hi. Thanks for help with this issue.
I have one more question. Did you make any option for change text in share buttons "Share this" or "Pin this" etc. This will be great to translate in other language ;)

I make some css for better look od cookie bar:
`
section.toolbelt_cookie_wrapper {
    display: flex;
    flex-direction: column;
    bottom: 30px;
    left: auto;
    right: 30px;
    max-width: 280px;
    background-color: rgba(255, 255, 255, .8);
    box-shadow: 0px 2px 15px 0px rgba(0, 0, 0, 0.25);
    border-radius: 5px
}

.toolbelt_cookie_wrapper button {
    font-size: 14px;
    background: #3A4A5D !important;
    color: #fff;
    font-weight: 300;
    width: 150px;
    text-align: center;
    transform: translateX(-50%);
    margin-left: 50%;
    border-radius: 4px;
    border: none;
    transition: all .2s ease-in-out;
}

.toolbelt_cookie_wrapper button:hover {
    background: #3e5f7a !important;
}

.toolbelt_cookie_wrapper strong {
    background: #fff;
    color: #3A4A5D !important;
    font-weight: 300;
    font-size: 14px;
}

section.toolbelt_social_share a {
  border-radius: 5px;
  font-size: 13px;
}

section.toolbelt_social_share a svg {
  width: 14px;
  height: 14px;
}

section.toolbelt_social_share a:hover,
section.toolbelt_social_share a:active,
section.toolbelt_social_share a:focus {
  text-decoration: none;
  opacity: .8;
}
`

**Comment by naymapl** [comment]
And one more think - when you plan to update this version for new one ? Thanks a lot for answer and all the best.

**Comment by BinaryMoon** [comment]
The previous changes were published yesterday.

All of the text is setup to be translated in the normal WordPress way.

I have customizing the social share options on my todo list, but I haven't worked out a nice way to do it yet.

**Comment by naymapl** [comment]
But I can't find any .po or .mo file to make translation. This is the best way and I can make full Polish translation of your plugin if you want. Thanks for any information about this.

**Comment by BinaryMoon** [comment]
I wasn't sure if I should include them in the plugin or not.

I shall generate them this evening and add them to the plugin.

**Comment by naymapl** [comment]
This will be nice to have .mo and .po files to translate. But from other way what you mean "All of the text is setup to be translated in the normal WordPress way." ?? What is it. I just always translate everything from .mo files on Poedit app. Is it any other simpless way to doing it ??

**Comment by BinaryMoon** [comment]
The best way to do it is through the WordPress plugin translation system. @pixolin has translated it into German, and now everyone can use it!

<img width="1033" alt="Screenshot 2019-09-05 at 12 20 23" src="https://user-images.githubusercontent.com/1004130/64337590-98ccfd00-cfd7-11e9-899c-ea0e6fea19ee.png">

There's info on the translator handbook on how to contribute.
https://make.wordpress.org/polyglots/handbook/tools/glotpress-translate-wordpress-org/

The Polish translation for Toolbelt is here:
https://translate.wordpress.org/locale/pl/default/wp-plugins/wp-toolbelt/

Once the translations have been added and translated the content can be installed and updated through the WordPress admin for anyone who uses WordPress in Polish.

**Comment by pixolin** [comment]
You _could_ add a translation template `/languages/wp-toolbelt.pot` for those who want to translate the plugin for personal use, only. However this isn't necessary for translations in the WordPress repository, which provides the translation for many.

To automize things, this Gulp package might be handy: https://github.com/wp-pot/gulp-wp-pot

**Comment by BinaryMoon** [comment]
@pixolin thanks for the info. I don't have a problem adding the pot file but wasn't sure if it would conflict with the plugin repository translations which is why I hadn't done it before.

**Comment by pixolin** [comment]
> The translation system looks through all PHP files in a plugin and finds each gettext call, including __() and _e(). For this reason, .po/.pot files are not needed to import, however they’re a great way of ensuring your entire plugin is completely internationalized.
Source: [Translations Handbook](https://make.wordpress.org/meta/handbook/documentation/translations/)

**Comment by BinaryMoon** [comment]
I've added it - generated with wp-pot automagically.

Also spotted an incorrect text domain.

**Comment by naymapl** [comment]
Hi. I translate almost everything for polish lang on this website: https://translate.wordpress.org/locale/pl/default/wp-plugins/wp-toolbelt/
but I think you need to check and accept.

**Comment by pixolin** [comment]
@naymapl You need a validator from the Polish polyglots team (listed [here](https://translate.wordpress.org/locale/pl/default/wp-plugins/wp-toolbelt/)) to look over the translated text strings. Once the translations are validated, they get distributed to every website running the plugin in Polish.

**Comment by naymapl** [comment]
@pixolin - thanks for advice - I ask somebody to validate this translation. Hope so I find somebody.

**Comment by pixolin** [comment]
You can also ask to get privileges as Project Translation Editor. Your local team has set up a web page which describes how translations are validated, where you can ask for help and what needs to be done to get assigned as PTE: https://pl.wordpress.org/pomoz-w-tlumaczeniu/

**Comment by naymapl** [comment]
@pixolin - thank you - I ask on slack chanel to check it and aprove. Hope so will be ok.

**Comment by naymapl** [comment]
@BinaryMoon - hi - i try to use translate made from /languages/wp-toolbelt.pot but is not working. Did you implement it in your plugin or I doing something wrong.

I create and translate this 2 files: 

wp-toolbelt-pl_PL.mo
wp-toolbelt-pl_PL.po

and copy them to wp-content/languages and/or wp-content/languages/plugins but they don`t work well.

**Comment by naymapl** [comment]
Ok - is working fine right now - need to update plugin to 1.8 ver.

**Comment by BinaryMoon** [comment]
A few fixes were published in 1.8 that made it all work properly. Great to hear it's working now! :)
