### ISSUE TITLE
Problem with cookie banner

### ISSUE THREAD

**Issue by naymapl** [BinaryMoon/wp-toolbelt#22]
Hi. I`m testing cookie banner.

I`m use this function on my website:

```
function my_cookies_accepted() {
  ?>
  console.log( 'cookies accepted' );
  <?php
  }
  add_action( 'toolbelt_cookies_accepted', 'my_cookies_accepted' );

  function my_cookie_banner_message( $message ) {
    return 'Strona wykorzystuje pliki cookies w celu prawidłowego funkcjonowania oraz możliwości korzystania z narzędzi analitycznych, reklamowych i społecznościowych. Szczegóły ich wykorzystania znajdziesz w: <a href="/polityka-prywatnosci-i-plikow-cookie/">Polityka prywatności i plików cookie.</a>';
}
add_filter( 'toolbelt_cookie_message', 'my_cookie_banner_message' );

function my_cookie_button_text( $text ) {
  $text['accept'] = 'Ok, zgadzam się';
  return $text;
}
add_filter( 'toolbelt_cookie_button_text', 'my_cookie_button_text' );
```
After click ok banner dissapear and looks ok. But after refresh page is show off again and every time you click ok nothing happends. What I doing wrong ??

Link to website: https://eallora.pl/

**Comment by BinaryMoon** [comment]
I think the problem is your custom styles. Remove display: flex from section.toolbelt_cookie_wrapper.

The plugin adds the display flex property when the bar is displayed, it should be display none by default.

**Comment by naymapl** [comment]
Thank you - this help and now looks like runing well.
