### ISSUE TITLE
[ask for explaination] of fast 404

### ISSUE THREAD

**Issue by ibes** [BinaryMoon/wp-toolbelt#42]
Do I get it right, that - without your or another plugin - when there is an eg image that is not found it will be answered with a 404.
And that 404 page is the WordPress 404 page that also is loaded if a blog post is not found. 

So instead of an image all the resources etc. of the 404 page will be loaded?

And your plugin supresses that, right?
What happens instead?
(Will check the code in a minute - want to ask anyway + want to encourage to add a sentence to the doc)

**Comment by BinaryMoon** [comment]
Hi there. And yes, you're right. If there's a 404 it will make a request to the 404 page. So if an image is missing it will attempt to load the 404 page instead.

The Fast 404 module tries to quit earlier, and just displays a text message for static files like images and whatnot.

Assuming you know PHP the code is very simple. You can see it here:
https://github.com/BinaryMoon/wp-toolbelt/blob/master/modules/fast-404/module.php

**Comment by pixolin** [comment]
I wonder if that could be extended to providing a 403 error in case `readme.txt` or `readme.md` files are retrieved to sniff for (vulnerable) plugins. Experienced users might have added a rule to their `.htaccess` to prohibit access to all `.txt` and `.md`-files anyway, but for the others returning a faster 403 may provide some additional gain in performance.

**Comment by BinaryMoon** [comment]
@pixolin I don't think that can be done at the php level unfortunately. I think the htaccess has a rule that skips files that already exist so that they don't get processed at all.

**Comment by szepeviktor** [comment]
> I wonder if that could be extended to providing a 403 error in case `readme.txt` or `readme.md` files are retrieved to sniff for (vulnerable) plugins

There is a huge list for [securing WordPress](https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/WordPress-security.md) including `wordpress.inc.conf` that does just that
