### ISSUE TITLE
Admin menu items not translatable

### ISSUE THREAD

**Issue by pixolin** [BinaryMoon/wp-toolbelt#50]
Currently the admin menu `Toolbelt` shows three menu items `Toolbelt`, `Settings` and `Tools`, which aren't translatable due to a missing function.

**Comment by BinaryMoon** [comment]
Thanks!

Regarding the Toolbelt translation specifically - would you actually translate that? Since it's almost a brand name would you change it or keep it the same?

I assumed it wouldn't change but I don't actually know what normally happens here.

**Comment by pixolin** [comment]
That's why I added the [description for translators](https://codex.wordpress.org/I18n_for_WordPress_Developers#Descriptions): `/* translators: plugin name */`

This description indicates, that the text string is referring to the plugin name. According to polyglot's translation handbook, plugin names shouldn't be translated. Yet adding the translation function seems to me as most consistent solution.

**Comment by BinaryMoon** [comment]
That's great. Makes total sense. Thanks for the clarification.
