### ISSUE TITLE
Enhance usability with better menu titles

### ISSUE THREAD

**Issue by pixolin** [BinaryMoon/wp-toolbelt#52]
The backend menu `Toolbelt` shows three menu items named `Toolbelt`, `Settings` and `Tools`. The difference between these submenus isn't obvious. To enhance usability I may suggest to rename them after their content and also reorder them with `Advanced Settings` as last menu item:

### Toolbelt
- Modules
- Module Properties
- Advanced Settings 

(It would be my pleasure to add a pull request, if you agree to these changes.)

**Comment by BinaryMoon** [comment]
Thanks for the feedback.

I like the idea of making the titles clearer. I'm not sure these are quite right though.

Changing Toolbelt to Modules makes total sense. I wonder if that would be enough on it's own though?

The Settings could be module properties - but to me they mean similar things?

The tools one isn't really advanced settings though. They are actions that change content not directly related to the toolbelt settings. For example if you are using Toolbelt projects then there is a tool to swap Jetpack Projects to Toolbelt Projects.

These are quite big database changes but they don't affect the behaviour of the actual modules.

**Comment by pixolin** [comment]
> I like the idea of making the titles clearer. I'm not sure these are quite right though.

Neither am I. It also depends much on your future plans to extend these submenus.

> Changing Toolbelt to Modules makes total sense. 

I like the term "modules" as it explains, you have a set of functions to alter your website and may select them to your needs. `Select Modules` (or just `Modules` to keep it short) seems to fit perfectly.

> The Settings could be module properties - but to me they mean similar things?

The problem really is, that at the moment the used terms all seem very similar. 
Imagine you need to explain somebody the usage in a support forum or by phone: 
"No, the page `toolbelt-tools` doesn't show the tools of the toolbelt, but a tool for one of the modules…"

**Comment by BinaryMoon** [comment]
Just to let you know I'm currently on holiday and the internet is worse than I expected (ie there isn't any) so I'll get back to this next week. I'm not ignoring it! :)

**Comment by BinaryMoon** [comment]
I've been thinking about this some more.

I think we should definitely change Toolbelt to Modules. That makes 100% sense.

For the other two - the names currently match the names used by WordPress (Settings, and Tools) as two distinct things. In English this makes sense to me, but I don't know if it does in German?

**Comment by pixolin** [comment]
This gives us

### Toolbelt
* Modules
* Settings
* Tools

Modules and Settings is perfectly fine for me. 
I hesitate with Toolbelt > Tools though as it seems too ambiguous. Another word describing what can be done, would perhaps make it more transparent?

**Comment by BinaryMoon** [comment]
How about:

* Modules
* Settings
* Processes

**Comment by BinaryMoon** [comment]
Awesome - gonna be in the next release then!
