### ISSUE TITLE
Wrapping modules in classes

### ISSUE THREAD

**Issue by szepeviktor** [BinaryMoon/wp-toolbelt#74]
If you use classes instead of global functions you may benefit from the brand new annotation based hooking
https://github.com/szepeviktor/Toolkit4WP/blob/master/src/HookAnnotation.php#L25

```php
namespace BinaryMoon\WpToolbelt;

use Toolkit4WP\HookAnnotation;

class AdminTweaks
{
    use HookAnnotation;

    public function __construct()
    {
        $this->hookMethods();
    }

    /**
     * Display some custom css to tweak the WordPress admin.
     *
     * @hook admin_head 20
     */
    public function adminTweaks() {
		...
	}
}
```

**Comment by szepeviktor** [comment]
If you prefer - which I second - a central controller:

```php
(new AdminTweaks())->hookMethods();
```

Or! You could use a dependency injection container :)

**Comment by BinaryMoon** [comment]
I know what classes are, and I can use them, I've even written a few. But it's not something I feel comfortable doing. Using simple functions just feels easier to me so it's what I tend to go for.

Same goes for namespaces.

**Comment by szepeviktor** [comment]
Okay-okay.
