### ISSUE TITLE
Infinite Scroll: "Load More" never hidden because HTML response is never empty

### ISSUE THREAD

**Issue by edavis** [BinaryMoon/wp-toolbelt#78]
Hello! Loving wp-toolbelt so far. Thanks for making it available.

Ran into an issue, I think, with Infinite Scroll:

It appears the intention in infiniteScroll.js is once the Loop has been exhausted and no more HTML is being returned, the "Load More" button should disappear.

However, because `<h6 class="toolbelt-divider">Page X<h6>` is prepended to the HTML an empty string is never returned and the button never disappears.

Thanks again for the plugin!

**Comment by BinaryMoon** [comment]
Hi there - thanks for the report. I shall look into this, hopefully I can work out what's going on.

**Comment by BinaryMoon** [comment]
I think I've solved this. It'll be in the next update.
