### ISSUE TITLE
Plugin adds toolbelt-properties CSS to frontend

### ISSUE THREAD

**Issue by patrickdanielsson** [BinaryMoon/wp-toolbelt#84]
Thank's for a great plugin. I have noticed that the plugin adds a CSS snippet to the frontend, is this needed?

`<style name="toolbelt-properties">:root { --toolbelt-spacing:1rem;}</style>`

**Comment by BinaryMoon** [comment]
Hi Patrick - thanks for the message. I am currently on holiday so not as responsive as normal :)

And yes, you're right. That snippet is added to the head. It's a css custom property that I use to control the spacing on elements that output html such as the related posts, and breadcrumbs etc. Using a single property means it can be easily overriden in your projects styles, and keep the spacing consistent across the site.

I guess the question I have is, are you not using any modules like related posts that output html that needs styling? I think my intention was that it would only output this css if it was needed but I may have missed something?

**Comment by BinaryMoon** [comment]
I have added a check that ensures the custom properties will only be included when modules that use them are activated. It will be in the next release

**Comment by patrickdanielsson** [comment]
Thanks for the support!

**Comment by BinaryMoon** [comment]
This is live now so I'm closing it. Thanks again for the report 😁
