### ISSUE TITLE
Insert class in the footnotes title

### ISSUE THREAD

**Issue by douglasferraz89** [BinaryMoon/wp-toolbelt#91]
I think it would be better for customizations if you put a class on h3.

The content of the footnotes is not in any div. This makes customizations difficult.

`$footnotes_markup[] = '<h3>' . esc_html__( 'Footnotes', 'wp-toolbelt' ) . '</h3>';`

One example:
`$footnotes_markup[] = '<h3 class="toolbelt-footnotes">' . esc_html__( 'Footnotes', 'wp-toolbelt' ) . '</h3>';`

**Comment by BinaryMoon** [comment]
Thanks for the feedback Douglas. I actually added this today after I replied to your tweet.

You can see the change in this commit in the dev branch:
https://github.com/BinaryMoon/wp-toolbelt/commit/daebcffccb144b37be4ca6c08a0e0273743fde6e

I went for a global heading class, and a specific one.

**Comment by douglasferraz89** [comment]
Perfect.
